### ISSUE TITLE
Add Mount Manager IOCTL

### ISSUE THREAD

**Issue by e2del** [tandasat/WinIoCtlDecoder#1]
Can you add IOCTL define in mountmgr.h ?

https://msdn.microsoft.com/en-us/library/windows/hardware/ff561593(v=vs.85).aspx

Thanks Eddy

**Comment by tandasat** [comment]
Thank you for your request. I have added the definition with commit 6a8d91d. Please take a look at the latest repository.

Best,

**Comment by tandasat** [comment]
Feel free to reopen the issue if the change does not suffice.
